### ISSUE TITLE
Using safe multisig cannot sign the eip712 messages to complete or reject grants

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/grants.buidlguidl.com#129]
I can send the 50% transaction but then when it captures the tx hash and I try to sign the message to complete the grant, I get an "Error completing" or "Error rejecting" if it was the action I was doing.

This is the console errors I had when trying to complete:

```
Uncaught (in promise) SwitchChainError
    at W.switchChain (560-6c90a744a9b2c549.js:1026:7826)
    at async W.getProvider (560-6c90a744a9b2c549.js:1026:6585)
    at async Promise.all (index 0)
    at async W.getWalletClient (560-6c90a744a9b2c549.js:1026:6675)
    at async ta (8474-80fe7fbb67464fff.js:20:11396)
    at async n (8474-80fe7fbb67464fff.js:20:11744)Caused by: TypeError: Cannot set properties of undefined (setting 'defaultChain')
    at nm.onChainChanged (4817.433a57a23d6241f0.js:33:29553)
    at i.<anonymous> (4817.433a57a23d6241f0.js:33:28293)
    at i.emit (9097-1a60dea03350292a.js:1:82503)
    at nr.setDefaultChain (4817.433a57a23d6241f0.js:33:10503)
    at nr.handleSwitchChain (4817.433a57a23d6241f0.js:33:11777)
    at nr.request (4817.433a57a23d6241f0.js:33:10113)
    at nm.request (4817.433a57a23d6241f0.js:33:22760)
    at nj.request (4817.433a57a23d6241f0.js:33:31782)
    at W.switchChain (560-6c90a744a9b2c549.js:1026:7639)
    at async W.getProvider (560-6c90a744a9b2c549.js:1026:6585)
4938-addd67e57688a2ff.js:1 Object TypeError: Cannot set properties of undefined (setting 'defaultChain')
    at nm.onChainChanged (4817.433a57a23d6241f0.js:33:29553)
    at i.<anonymous> (4817.433a57a23d6241f0.js:33:28293)
    at i.emit (9097-1a60dea03350292a.js:1:82503)
    at nr.setDefaultChain (4817.433a57a23d6241f0.js:33:10503)
    at nm.onChainChanged (4817.433a57a23d6241f0.js:33:29460)
    at i.<anonymous> (4817.433a57a23d6241f0.js:33:27726)
    at i.emit (9097-1a60dea03350292a.js:1:82503)
    at iq.onSessionEventRequest (4817.433a57a23d6241f0.js:7:99774)
    at iq.processRequest (4817.433a57a23d6241f0.js:7:93280)
    at iq.processRequestsQueue (4817.433a57a23d6241f0.js:7:92614)
window.console.error @ 4938-addd67e57688a2ff.js:1
api/grants/7ABG3zfmbBiVJYsv37UG/review:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
api/grants/rvVEKZkm7kj9cL5zg6lC/review:1 
        
        
       Failed to load resource: the server responded with a status of 401 ()
```

**Comment by technophile-04** [comment]
Completed at #135
